/*
 * File: calc_lead_vehicle.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand,
 *   you must change it only in the area defined as:
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text'
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  -------------------------------------------------------------------------
 * Created: Wed Nov 30 13:20:15 2016
 */

#define S_FUNCTION_LEVEL               2
#define S_FUNCTION_NAME                calc_lead_vehicle

/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS                     16

/* Input Port  0 */
#define IN_PORT_0_NAME                 ACC_Enable
#define INPUT_0_WIDTH                  1
#define INPUT_DIMS_0_COL               1
#define INPUT_0_DTYPE                  boolean_T
#define INPUT_0_COMPLEX                COMPLEX_NO
#define IN_0_FRAME_BASED               FRAME_NO
#define IN_0_BUS_BASED                 0
#define IN_0_BUS_NAME
#define IN_0_DIMS                      1-D
#define INPUT_0_FEEDTHROUGH            1
#define IN_0_ISSIGNED                  0
#define IN_0_WORDLENGTH                8
#define IN_0_FIXPOINTSCALING           1
#define IN_0_FRACTIONLENGTH            9
#define IN_0_BIAS                      0
#define IN_0_SLOPE                     0.125

/* Input Port  1 */
#define IN_PORT_1_NAME                 s1
#define INPUT_1_WIDTH                  1
#define INPUT_DIMS_1_COL               1
#define INPUT_1_DTYPE                  real32_T
#define INPUT_1_COMPLEX                COMPLEX_NO
#define IN_1_FRAME_BASED               FRAME_NO
#define IN_1_BUS_BASED                 0
#define IN_1_BUS_NAME
#define IN_1_DIMS                      1-D
#define INPUT_1_FEEDTHROUGH            1
#define IN_1_ISSIGNED                  0
#define IN_1_WORDLENGTH                8
#define IN_1_FIXPOINTSCALING           1
#define IN_1_FRACTIONLENGTH            9
#define IN_1_BIAS                      0
#define IN_1_SLOPE                     0.125

/* Input Port  2 */
#define IN_PORT_2_NAME                 s2
#define INPUT_2_WIDTH                  1
#define INPUT_DIMS_2_COL               1
#define INPUT_2_DTYPE                  real32_T
#define INPUT_2_COMPLEX                COMPLEX_NO
#define IN_2_FRAME_BASED               FRAME_NO
#define IN_2_BUS_BASED                 0
#define IN_2_BUS_NAME
#define IN_2_DIMS                      1-D
#define INPUT_2_FEEDTHROUGH            1
#define IN_2_ISSIGNED                  0
#define IN_2_WORDLENGTH                8
#define IN_2_FIXPOINTSCALING           1
#define IN_2_FRACTIONLENGTH            9
#define IN_2_BIAS                      0
#define IN_2_SLOPE                     0.125

/* Input Port  3 */
#define IN_PORT_3_NAME                 s3
#define INPUT_3_WIDTH                  1
#define INPUT_DIMS_3_COL               1
#define INPUT_3_DTYPE                  real32_T
#define INPUT_3_COMPLEX                COMPLEX_NO
#define IN_3_FRAME_BASED               FRAME_NO
#define IN_3_BUS_BASED                 0
#define IN_3_BUS_NAME
#define IN_3_DIMS                      1-D
#define INPUT_3_FEEDTHROUGH            1
#define IN_3_ISSIGNED                  0
#define IN_3_WORDLENGTH                8
#define IN_3_FIXPOINTSCALING           1
#define IN_3_FRACTIONLENGTH            9
#define IN_3_BIAS                      0
#define IN_3_SLOPE                     0.125

/* Input Port  4 */
#define IN_PORT_4_NAME                 s4
#define INPUT_4_WIDTH                  1
#define INPUT_DIMS_4_COL               1
#define INPUT_4_DTYPE                  real32_T
#define INPUT_4_COMPLEX                COMPLEX_NO
#define IN_4_FRAME_BASED               FRAME_NO
#define IN_4_BUS_BASED                 0
#define IN_4_BUS_NAME
#define IN_4_DIMS                      1-D
#define INPUT_4_FEEDTHROUGH            1
#define IN_4_ISSIGNED                  0
#define IN_4_WORDLENGTH                8
#define IN_4_FIXPOINTSCALING           1
#define IN_4_FRACTIONLENGTH            9
#define IN_4_BIAS                      0
#define IN_4_SLOPE                     0.125

/* Input Port  5 */
#define IN_PORT_5_NAME                 s5
#define INPUT_5_WIDTH                  1
#define INPUT_DIMS_5_COL               1
#define INPUT_5_DTYPE                  real32_T
#define INPUT_5_COMPLEX                COMPLEX_NO
#define IN_5_FRAME_BASED               FRAME_NO
#define IN_5_BUS_BASED                 0
#define IN_5_BUS_NAME
#define IN_5_DIMS                      1-D
#define INPUT_5_FEEDTHROUGH            1
#define IN_5_ISSIGNED                  0
#define IN_5_WORDLENGTH                8
#define IN_5_FIXPOINTSCALING           1
#define IN_5_FRACTIONLENGTH            9
#define IN_5_BIAS                      0
#define IN_5_SLOPE                     0.125

/* Input Port  6 */
#define IN_PORT_6_NAME                 s6
#define INPUT_6_WIDTH                  1
#define INPUT_DIMS_6_COL               1
#define INPUT_6_DTYPE                  real32_T
#define INPUT_6_COMPLEX                COMPLEX_NO
#define IN_6_FRAME_BASED               FRAME_NO
#define IN_6_BUS_BASED                 0
#define IN_6_BUS_NAME
#define IN_6_DIMS                      1-D
#define INPUT_6_FEEDTHROUGH            1
#define IN_6_ISSIGNED                  0
#define IN_6_WORDLENGTH                8
#define IN_6_FIXPOINTSCALING           1
#define IN_6_FRACTIONLENGTH            9
#define IN_6_BIAS                      0
#define IN_6_SLOPE                     0.125

/* Input Port  7 */
#define IN_PORT_7_NAME                 s
#define INPUT_7_WIDTH                  1
#define INPUT_DIMS_7_COL               1
#define INPUT_7_DTYPE                  real32_T
#define INPUT_7_COMPLEX                COMPLEX_NO
#define IN_7_FRAME_BASED               FRAME_NO
#define IN_7_BUS_BASED                 0
#define IN_7_BUS_NAME
#define IN_7_DIMS                      1-D
#define INPUT_7_FEEDTHROUGH            1
#define IN_7_ISSIGNED                  0
#define IN_7_WORDLENGTH                8
#define IN_7_FIXPOINTSCALING           1
#define IN_7_FRACTIONLENGTH            9
#define IN_7_BIAS                      0
#define IN_7_SLOPE                     0.125

/* Input Port  8 */
#define IN_PORT_8_NAME                 us1
#define INPUT_8_WIDTH                  1
#define INPUT_DIMS_8_COL               1
#define INPUT_8_DTYPE                  real32_T
#define INPUT_8_COMPLEX                COMPLEX_NO
#define IN_8_FRAME_BASED               FRAME_NO
#define IN_8_BUS_BASED                 0
#define IN_8_BUS_NAME
#define IN_8_DIMS                      1-D
#define INPUT_8_FEEDTHROUGH            1
#define IN_8_ISSIGNED                  0
#define IN_8_WORDLENGTH                8
#define IN_8_FIXPOINTSCALING           1
#define IN_8_FRACTIONLENGTH            9
#define IN_8_BIAS                      0
#define IN_8_SLOPE                     0.125

/* Input Port  9 */
#define IN_PORT_9_NAME                 us2
#define INPUT_9_WIDTH                  1
#define INPUT_DIMS_9_COL               1
#define INPUT_9_DTYPE                  real32_T
#define INPUT_9_COMPLEX                COMPLEX_NO
#define IN_9_FRAME_BASED               FRAME_NO
#define IN_9_BUS_BASED                 0
#define IN_9_BUS_NAME
#define IN_9_DIMS                      1-D
#define INPUT_9_FEEDTHROUGH            1
#define IN_9_ISSIGNED                  0
#define IN_9_WORDLENGTH                8
#define IN_9_FIXPOINTSCALING           1
#define IN_9_FRACTIONLENGTH            9
#define IN_9_BIAS                      0
#define IN_9_SLOPE                     0.125

/* Input Port  10 */
#define IN_PORT_10_NAME                us3
#define INPUT_10_WIDTH                 1
#define INPUT_DIMS_10_COL              1
#define INPUT_10_DTYPE                 real32_T
#define INPUT_10_COMPLEX               COMPLEX_NO
#define IN_10_FRAME_BASED              FRAME_NO
#define IN_10_BUS_BASED                0
#define IN_10_BUS_NAME
#define IN_10_DIMS                     1-D
#define INPUT_10_FEEDTHROUGH           1
#define IN_10_ISSIGNED                 0
#define IN_10_WORDLENGTH               8
#define IN_10_FIXPOINTSCALING          1
#define IN_10_FRACTIONLENGTH           9
#define IN_10_BIAS                     0
#define IN_10_SLOPE                    0.125

/* Input Port  11 */
#define IN_PORT_11_NAME                us4
#define INPUT_11_WIDTH                 1
#define INPUT_DIMS_11_COL              1
#define INPUT_11_DTYPE                 real32_T
#define INPUT_11_COMPLEX               COMPLEX_NO
#define IN_11_FRAME_BASED              FRAME_NO
#define IN_11_BUS_BASED                0
#define IN_11_BUS_NAME
#define IN_11_DIMS                     1-D
#define INPUT_11_FEEDTHROUGH           1
#define IN_11_ISSIGNED                 0
#define IN_11_WORDLENGTH               8
#define IN_11_FIXPOINTSCALING          1
#define IN_11_FRACTIONLENGTH           9
#define IN_11_BIAS                     0
#define IN_11_SLOPE                    0.125

/* Input Port  12 */
#define IN_PORT_12_NAME                us5
#define INPUT_12_WIDTH                 1
#define INPUT_DIMS_12_COL              1
#define INPUT_12_DTYPE                 real32_T
#define INPUT_12_COMPLEX               COMPLEX_NO
#define IN_12_FRAME_BASED              FRAME_NO
#define IN_12_BUS_BASED                0
#define IN_12_BUS_NAME
#define IN_12_DIMS                     1-D
#define INPUT_12_FEEDTHROUGH           1
#define IN_12_ISSIGNED                 0
#define IN_12_WORDLENGTH               8
#define IN_12_FIXPOINTSCALING          1
#define IN_12_FRACTIONLENGTH           9
#define IN_12_BIAS                     0
#define IN_12_SLOPE                    0.125

/* Input Port  13 */
#define IN_PORT_13_NAME                us6
#define INPUT_13_WIDTH                 1
#define INPUT_DIMS_13_COL              1
#define INPUT_13_DTYPE                 real32_T
#define INPUT_13_COMPLEX               COMPLEX_NO
#define IN_13_FRAME_BASED              FRAME_NO
#define IN_13_BUS_BASED                0
#define IN_13_BUS_NAME
#define IN_13_DIMS                     1-D
#define INPUT_13_FEEDTHROUGH           1
#define IN_13_ISSIGNED                 0
#define IN_13_WORDLENGTH               8
#define IN_13_FIXPOINTSCALING          1
#define IN_13_FRACTIONLENGTH           9
#define IN_13_BIAS                     0
#define IN_13_SLOPE                    0.125

/* Input Port  14 */
#define IN_PORT_14_NAME                us
#define INPUT_14_WIDTH                 1
#define INPUT_DIMS_14_COL              1
#define INPUT_14_DTYPE                 real32_T
#define INPUT_14_COMPLEX               COMPLEX_NO
#define IN_14_FRAME_BASED              FRAME_NO
#define IN_14_BUS_BASED                0
#define IN_14_BUS_NAME
#define IN_14_DIMS                     1-D
#define INPUT_14_FEEDTHROUGH           1
#define IN_14_ISSIGNED                 0
#define IN_14_WORDLENGTH               8
#define IN_14_FIXPOINTSCALING          1
#define IN_14_FRACTIONLENGTH           9
#define IN_14_BIAS                     0
#define IN_14_SLOPE                    0.125

/* Input Port  15 */
#define IN_PORT_15_NAME                H
#define INPUT_15_WIDTH                 1
#define INPUT_DIMS_15_COL              1
#define INPUT_15_DTYPE                 real_T
#define INPUT_15_COMPLEX               COMPLEX_NO
#define IN_15_FRAME_BASED              FRAME_NO
#define IN_15_BUS_BASED                0
#define IN_15_BUS_NAME
#define IN_15_DIMS                     1-D
#define INPUT_15_FEEDTHROUGH           1
#define IN_15_ISSIGNED                 0
#define IN_15_WORDLENGTH               8
#define IN_15_FIXPOINTSCALING          1
#define IN_15_FRACTIONLENGTH           9
#define IN_15_BIAS                     0
#define IN_15_SLOPE                    0.125
#define NUM_OUTPUTS                    5

/* Output Port  0 */
#define OUT_PORT_0_NAME                en_man
#define OUTPUT_0_WIDTH                 1
#define OUTPUT_DIMS_0_COL              1
#define OUTPUT_0_DTYPE                 boolean_T
#define OUTPUT_0_COMPLEX               COMPLEX_NO
#define OUT_0_FRAME_BASED              FRAME_NO
#define OUT_0_BUS_BASED                0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS                     1-D
#define OUT_0_ISSIGNED                 1
#define OUT_0_WORDLENGTH               8
#define OUT_0_FIXPOINTSCALING          1
#define OUT_0_FRACTIONLENGTH           3
#define OUT_0_BIAS                     0
#define OUT_0_SLOPE                    0.125

/* Output Port  1 */
#define OUT_PORT_1_NAME                en_vel
#define OUTPUT_1_WIDTH                 1
#define OUTPUT_DIMS_1_COL              1
#define OUTPUT_1_DTYPE                 boolean_T
#define OUTPUT_1_COMPLEX               COMPLEX_NO
#define OUT_1_FRAME_BASED              FRAME_NO
#define OUT_1_BUS_BASED                0
#define OUT_1_BUS_NAME
#define OUT_1_DIMS                     1-D
#define OUT_1_ISSIGNED                 1
#define OUT_1_WORDLENGTH               8
#define OUT_1_FIXPOINTSCALING          1
#define OUT_1_FRACTIONLENGTH           3
#define OUT_1_BIAS                     0
#define OUT_1_SLOPE                    0.125

/* Output Port  2 */
#define OUT_PORT_2_NAME                en_pos
#define OUTPUT_2_WIDTH                 1
#define OUTPUT_DIMS_2_COL              1
#define OUTPUT_2_DTYPE                 boolean_T
#define OUTPUT_2_COMPLEX               COMPLEX_NO
#define OUT_2_FRAME_BASED              FRAME_NO
#define OUT_2_BUS_BASED                0
#define OUT_2_BUS_NAME
#define OUT_2_DIMS                     1-D
#define OUT_2_ISSIGNED                 1
#define OUT_2_WORDLENGTH               8
#define OUT_2_FIXPOINTSCALING          1
#define OUT_2_FRACTIONLENGTH           3
#define OUT_2_BIAS                     0
#define OUT_2_SLOPE                    0.125

/* Output Port  3 */
#define OUT_PORT_3_NAME                lead_s
#define OUTPUT_3_WIDTH                 1
#define OUTPUT_DIMS_3_COL              1
#define OUTPUT_3_DTYPE                 real32_T
#define OUTPUT_3_COMPLEX               COMPLEX_NO
#define OUT_3_FRAME_BASED              FRAME_NO
#define OUT_3_BUS_BASED                0
#define OUT_3_BUS_NAME
#define OUT_3_DIMS                     1-D
#define OUT_3_ISSIGNED                 1
#define OUT_3_WORDLENGTH               8
#define OUT_3_FIXPOINTSCALING          1
#define OUT_3_FRACTIONLENGTH           3
#define OUT_3_BIAS                     0
#define OUT_3_SLOPE                    0.125

/* Output Port  4 */
#define OUT_PORT_4_NAME                lead_us
#define OUTPUT_4_WIDTH                 1
#define OUTPUT_DIMS_4_COL              1
#define OUTPUT_4_DTYPE                 real32_T
#define OUTPUT_4_COMPLEX               COMPLEX_NO
#define OUT_4_FRAME_BASED              FRAME_NO
#define OUT_4_BUS_BASED                0
#define OUT_4_BUS_NAME
#define OUT_4_DIMS                     1-D
#define OUT_4_ISSIGNED                 1
#define OUT_4_WORDLENGTH               8
#define OUT_4_FIXPOINTSCALING          1
#define OUT_4_FRACTIONLENGTH           3
#define OUT_4_BIAS                     0
#define OUT_4_SLOPE                    0.125
#define NPARAMS                        0
#define SAMPLE_TIME_0                  INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES                0
#define DISC_STATES_IC                 [0]
#define NUM_CONT_STATES                0
#define CONT_STATES_IC                 [0]
#define SFUNWIZ_GENERATE_TLC           1
#define SOURCEFILES                    "__SFB__"
#define PANELINDEX                     6
#define USE_SIMSTRUCT                  0
#define SHOW_COMPILE_STEPS             1
#define CREATE_DEBUG_MEXFILE           1
#define SAVE_CODE_ONLY                 0
#define SFUNWIZ_REVISION               3.0

/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"

extern void calc_lead_vehicle_Outputs_wrapper(const boolean_T *ACC_Enable,
  const real32_T *s1,
  const real32_T *s2,
  const real32_T *s3,
  const real32_T *s4,
  const real32_T *s5,
  const real32_T *s6,
  const real32_T *s,
  const real32_T *us1,
  const real32_T *us2,
  const real32_T *us3,
  const real32_T *us4,
  const real32_T *us5,
  const real32_T *us6,
  const real32_T *us,
  const real_T *H,
  boolean_T *en_man,
  boolean_T *en_vel,
  boolean_T *en_pos,
  real32_T *lead_s,
  real32_T *lead_us);

/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(inputDimsInfo);
  DECL_AND_INIT_DIMSINFO(outputDimsInfo);
  ssSetNumSFcnParams(S, NPARAMS);
  if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
    return;                            /* Parameter mismatch will be reported by Simulink */
  }

  ssSetNumContStates(S, NUM_CONT_STATES);
  ssSetNumDiscStates(S, NUM_DISC_STATES);
  if (!ssSetNumInputPorts(S, NUM_INPUTS))
    return;

  /*Input Port 0 */
  ssSetInputPortWidth(S, 0, INPUT_0_WIDTH);/* */
  ssSetInputPortDataType(S, 0, SS_BOOLEAN);
  ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 0, 1);/*direct input signal access*/

  /*Input Port 1 */
  ssSetInputPortWidth(S, 1, INPUT_1_WIDTH);/* */
  ssSetInputPortDataType(S, 1, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 1, 1);/*direct input signal access*/

  /*Input Port 2 */
  ssSetInputPortWidth(S, 2, INPUT_2_WIDTH);/* */
  ssSetInputPortDataType(S, 2, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 2, INPUT_2_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 2, 1);/*direct input signal access*/

  /*Input Port 3 */
  ssSetInputPortWidth(S, 3, INPUT_3_WIDTH);/* */
  ssSetInputPortDataType(S, 3, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 3, INPUT_3_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 3, INPUT_3_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 3, 1);/*direct input signal access*/

  /*Input Port 4 */
  ssSetInputPortWidth(S, 4, INPUT_4_WIDTH);/* */
  ssSetInputPortDataType(S, 4, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 4, INPUT_4_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 4, INPUT_4_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 4, 1);/*direct input signal access*/

  /*Input Port 5 */
  ssSetInputPortWidth(S, 5, INPUT_5_WIDTH);/* */
  ssSetInputPortDataType(S, 5, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 5, INPUT_5_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 5, INPUT_5_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 5, 1);/*direct input signal access*/

  /*Input Port 6 */
  ssSetInputPortWidth(S, 6, INPUT_6_WIDTH);/* */
  ssSetInputPortDataType(S, 6, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 6, INPUT_6_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 6, INPUT_6_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 6, 1);/*direct input signal access*/

  /*Input Port 7 */
  ssSetInputPortWidth(S, 7, INPUT_7_WIDTH);/* */
  ssSetInputPortDataType(S, 7, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 7, INPUT_7_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 7, INPUT_7_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 7, 1);/*direct input signal access*/

  /*Input Port 8 */
  ssSetInputPortWidth(S, 8, INPUT_8_WIDTH);/* */
  ssSetInputPortDataType(S, 8, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 8, INPUT_8_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 8, INPUT_8_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 8, 1);/*direct input signal access*/

  /*Input Port 9 */
  ssSetInputPortWidth(S, 9, INPUT_9_WIDTH);/* */
  ssSetInputPortDataType(S, 9, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 9, INPUT_9_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 9, INPUT_9_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 9, 1);/*direct input signal access*/

  /*Input Port 10 */
  ssSetInputPortWidth(S, 10, INPUT_10_WIDTH);/* */
  ssSetInputPortDataType(S, 10, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 10, INPUT_10_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 10, INPUT_10_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 10, 1);/*direct input signal access*/

  /*Input Port 11 */
  ssSetInputPortWidth(S, 11, INPUT_11_WIDTH);/* */
  ssSetInputPortDataType(S, 11, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 11, INPUT_11_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 11, INPUT_11_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 11, 1);/*direct input signal access*/

  /*Input Port 12 */
  ssSetInputPortWidth(S, 12, INPUT_12_WIDTH);/* */
  ssSetInputPortDataType(S, 12, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 12, INPUT_12_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 12, INPUT_12_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 12, 1);/*direct input signal access*/

  /*Input Port 13 */
  ssSetInputPortWidth(S, 13, INPUT_13_WIDTH);/* */
  ssSetInputPortDataType(S, 13, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 13, INPUT_13_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 13, INPUT_13_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 13, 1);/*direct input signal access*/

  /*Input Port 14 */
  ssSetInputPortWidth(S, 14, INPUT_14_WIDTH);/* */
  ssSetInputPortDataType(S, 14, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 14, INPUT_14_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 14, INPUT_14_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 14, 1);/*direct input signal access*/

  /*Input Port 15 */
  ssSetInputPortWidth(S, 15, INPUT_15_WIDTH);/* */
  ssSetInputPortDataType(S, 15, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 15, INPUT_15_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 15, INPUT_15_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 15, 1);/*direct input signal access*/
  if (!ssSetNumOutputPorts(S, NUM_OUTPUTS))
    return;

  /* Output Port 0 */
  ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
  ssSetOutputPortDataType(S, 0, SS_BOOLEAN);
  ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);

  /* Output Port 1 */
  ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
  ssSetOutputPortDataType(S, 1, SS_BOOLEAN);
  ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);

  /* Output Port 2 */
  ssSetOutputPortWidth(S, 2, OUTPUT_2_WIDTH);
  ssSetOutputPortDataType(S, 2, SS_BOOLEAN);
  ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);

  /* Output Port 3 */
  ssSetOutputPortWidth(S, 3, OUTPUT_3_WIDTH);
  ssSetOutputPortDataType(S, 3, SS_SINGLE);
  ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);

  /* Output Port 4 */
  ssSetOutputPortWidth(S, 4, OUTPUT_4_WIDTH);
  ssSetOutputPortDataType(S, 4, SS_SINGLE);
  ssSetOutputPortComplexSignal(S, 4, OUTPUT_4_COMPLEX);
  ssSetNumSampleTimes(S, 1);
  ssSetNumRWork(S, 0);
  ssSetNumIWork(S, 0);
  ssSetNumPWork(S, 0);
  ssSetNumModes(S, 0);
  ssSetNumNonsampledZCs(S, 0);
  ssSetSimulinkVersionGeneratedIn(S, "8.6");

  /* Take care when specifying exception free code - see sfuntmpl_doc.c */
  ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                   SS_OPTION_USE_TLC_WITH_ACCELERATOR |
                   SS_OPTION_WORKS_WITH_CODE_REUSE));
}

# define MDL_SET_INPUT_PORT_FRAME_DATA

static void mdlSetInputPortFrameData(SimStruct *S,
  int_T port,
  Frame_T frameData)
{
  ssSetInputPortFrameData(S, port, frameData);
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  ssSetSampleTime(S, 0, SAMPLE_TIME_0);
  ssSetModelReferenceSampleTimeDefaultInheritance(S);
  ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE

static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetInputPortDataType( S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE

static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES

static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType( S, 0, SS_DOUBLE);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  const boolean_T *ACC_Enable = (const boolean_T*) ssGetInputPortSignal(S,0);
  const real32_T *s1 = (const real32_T*) ssGetInputPortSignal(S,1);
  const real32_T *s2 = (const real32_T*) ssGetInputPortSignal(S,2);
  const real32_T *s3 = (const real32_T*) ssGetInputPortSignal(S,3);
  const real32_T *s4 = (const real32_T*) ssGetInputPortSignal(S,4);
  const real32_T *s5 = (const real32_T*) ssGetInputPortSignal(S,5);
  const real32_T *s6 = (const real32_T*) ssGetInputPortSignal(S,6);
  const real32_T *s = (const real32_T*) ssGetInputPortSignal(S,7);
  const real32_T *us1 = (const real32_T*) ssGetInputPortSignal(S,8);
  const real32_T *us2 = (const real32_T*) ssGetInputPortSignal(S,9);
  const real32_T *us3 = (const real32_T*) ssGetInputPortSignal(S,10);
  const real32_T *us4 = (const real32_T*) ssGetInputPortSignal(S,11);
  const real32_T *us5 = (const real32_T*) ssGetInputPortSignal(S,12);
  const real32_T *us6 = (const real32_T*) ssGetInputPortSignal(S,13);
  const real32_T *us = (const real32_T*) ssGetInputPortSignal(S,14);
  const real_T *H = (const real_T*) ssGetInputPortSignal(S,15);
  boolean_T *en_man = (boolean_T *)ssGetOutputPortRealSignal(S,0);
  boolean_T *en_vel = (boolean_T *)ssGetOutputPortRealSignal(S,1);
  boolean_T *en_pos = (boolean_T *)ssGetOutputPortRealSignal(S,2);
  real32_T *lead_s = (real32_T *)ssGetOutputPortRealSignal(S,3);
  real32_T *lead_us = (real32_T *)ssGetOutputPortRealSignal(S,4);
  calc_lead_vehicle_Outputs_wrapper(ACC_Enable, s1, s2, s3, s4, s5, s6, s, us1,
    us2, us3, us4, us5, us6, us, H, en_man, en_vel, en_pos, lead_s, lead_us);
}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
}

#ifdef MATLAB_MEX_FILE                 /* Is this file being compiled as a MEX-file? */
#include "simulink.c"                  /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"                   /* Code generation registration function */
#endif
