set MATLAB=C:\Program Files\MATLAB\R2015b
"C:\Program Files\MATLAB\R2015b\bin\win64\gmake" -f Final_project.mk  GENERATE_ERT_S_FUNCTION=0 INCLUDE_MDL_TERMINATE_FCN=1 COMBINE_OUTPUT_UPDATE_FCNS=1 MULTI_INSTANCE_CODE=0 INTEGER_CODE=0 ISPROTECTINGMODEL=NOTPROTECTING
